### ISSUE TITLE
이슈 프로세스 및 branch 관련된 GitHub config 변경

### ISSUE THREAD

**Issue by okyungjin** [dev-entually/DevCalendar#9]
# TODO
- [x] PR 이슈는 Approve 처리해야 Merge 할 수 있도록 설정한다.
- [x] Local에서 main 브랜치로 push를 막는 방법이 있는지 조사한다. (Git Hooks)
- [x] Default Branch를 develop으로 설정한다.

**Comment by GuruneLee** [comment]
[wiki - Branch Rules](https://github.com/dev-entually/DevCalendar/wiki/Branch-Rules)

**Comment by GuruneLee** [comment]
[wiki - Branch Rules](https://github.com/dev-entually/DevCalendar/wiki/Branch-Rules)

**Comment by okyungjin** [comment]
[프로젝트 관리](https://github.com/dev-entually/DevCalendar/wiki/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B4%80%EB%A6%AC) 문서에 통합하여 해당 이슈 Close 처리 합니다.
